# Docker Security Configuration
# This file contains security-related configurations for Docker containers

version: '3.8'

# Security-focused service extensions
x-security-common: &security-common
  security_opt:
    - no-new-privileges:true
    - apparmor:docker-default
  cap_drop:
    - ALL
  cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - SETGID
    - SETUID
  read_only: true
  tmpfs:
    - /tmp
    - /var/tmp
  user: "1000:1000"

x-logging-common: &logging-common
  logging:
    driver: json-file
    options:
      max-size: "10m"
      max-file: "3"
      labels: "service"

x-resource-limits: &resource-limits
  deploy:
    resources:
      limits:
        cpus: '0.5'
        memory: 512M
      reservations:
        cpus: '0.25'
        memory: 256M

# Health check configurations
x-healthcheck-web: &healthcheck-web
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:80/health"]
    interval: 30s
    timeout: 10s
    retries: 3
    start_period: 40s

x-healthcheck-tcp: &healthcheck-tcp
  healthcheck:
    test: ["CMD", "nc", "-z", "localhost", "5432"]
    interval: 30s
    timeout: 10s
    retries: 3
    start_period: 40s

# Network security configurations
networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1
    driver_opts:
      com.docker.network.bridge.name: docker-backend
      com.docker.network.bridge.enable_icc: "false"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
      com.docker.network.driver.mtu: "1500"
  
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1
    driver_opts:
      com.docker.network.bridge.name: docker-frontend
      com.docker.network.bridge.enable_icc: "false"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
      com.docker.network.driver.mtu: "1500"

# Secrets management (for Docker Swarm mode)
secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
  redis_password:
    file: ./secrets/redis_password.txt
  influxdb_admin_token:
    file: ./secrets/influxdb_admin_token.txt
  grafana_admin_password:
    file: ./secrets/grafana_admin_password.txt

# Configs for read-only configuration files
configs:
  nginx_config:
    file: ./config/nginx/nginx.prod.conf
  postgres_config:
    file: ./config/postgres/postgresql.prod.conf
  redis_config:
    file: ./config/redis/redis.prod.conf

# Volume configurations with security constraints
volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/postgres_data
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/redis_data
  influxdb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/influxdb_data
  grafana_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/grafana_data
