# Prometheus Configuration
# Global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alerting config
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

# Rule files
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Scrape configs
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'influxdb'
    static_configs:
      - targets: ['influxdb:8086']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'mqtt'
    static_configs:
      - targets: ['mosquitto:1883']
